import type { SessionLog, Technique } from "../types/domain";
import { localTodayIso } from "../utils/date";

const today = localTodayIso();

export const techniques: Technique[] = [
  {
    id: "tech-1",
    name: "Triangle from Guard",
    position: "Closed Guard",
    category: "Submission",
    level: "Beginner",
    tags: ["choke", "fundamental"],
    notes: "Break posture first, then angle off before locking.",
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-2",
    name: "Knee Cut Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Beginner",
    tags: ["pressure", "guard pass"],
    notes: "Control near-side underhook to avoid the back-take.",
    timesPracticed: 8,
    lastPracticed: today,
  },
  {
    id: "tech-3",
    name: "Scissor Sweep",
    position: "Guard",
    category: "Sweep",
    level: "Beginner",
    tags: ["fundamental", "off-balance"],
    notes: "Load their weight on your shin, pull sleeve and collar, then chop and come up.",
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-4",
    name: "Single Leg X Sweep",
    position: "Single Leg X",
    category: "Sweep",
    level: "Beginner",
    tags: ["ashi", "off-balance"],
    notes: "Off-balance with your outside foot and sleeve control, then elevate and turn them over.",
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-5",
    name: "Back Escape to Half Guard",
    position: "Back Control Defense",
    category: "Escape",
    level: "Beginner",
    tags: ["defense", "survival"],
    notes: "Control choking arm, clear the hook, and rotate hips to recover half guard.",
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-6",
    name: "Double Leg Takedown",
    position: "Standing",
    category: "Takedown",
    level: "Beginner",
    tags: ["wrestling", "entry"],
    notes: "Level change, head inside, run the pipe.",
    timesPracticed: 6,
    lastPracticed: today,
  },
  {
    id: "tech-7",
    name: "Arm Triangle from Mount",
    position: "Mount",
    category: "Submission",
    level: "Beginner",
    tags: ["choke", "control"],
    notes: "Walk to one side to isolate the shoulder, lock biceps, and finish with chest pressure.",
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-8",
    name: "Hip Bump Sweep",
    position: "Closed Guard",
    category: "Sweep",
    level: "Beginner",
    tags: ["fundamental", "kimura threat"],
    notes: "Post one hand, sit up hard, and drive hips across while posting the opposite foot.",
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-9",
    name: "Kimura from Side Control",
    position: "Side Control",
    category: "Submission",
    level: "Beginner",
    tags: ["shoulder lock", "top game"],
    notes: "Pin wrist to mat, figure-four the arm, and paintbrush the elbow toward the hip.",
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-10",
    name: "Granby Roll",
    position: "Turtle",
    category: "Escape",
    level: "Beginner",
    tags: ["inversion", "defense"],
    notes: "Tuck shoulder, roll over near side, and invert to recover guard or create space.",
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-11",
    name: "Body Lock Pass",
    position: "Half Guard Top",
    category: "Pass",
    level: "Beginner",
    tags: ["pressure", "smash pass"],
    notes: "Lock hands around hips, flatten their knees together, and walk around to side control.",
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-12",
    name: "Berimbolo Entry",
    position: "DLR",
    category: "Sweep",
    level: "Intermediate",
    tags: ["leg entanglement", "back take"],
    notes: "Invert under DLR hooks, connect hips behind theirs, and climb to seatbelt control.",
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-13",
    name: "Cross Collar Choke",
    position: "Mount",
    category: "Submission",
    level: "Beginner",
    tags: ["gi", "fundamental"],
    notes: "Deep cross-collar grip first, feed second hand palm-up, then drop elbows to finish.",
    timesPracticed: 7,
    lastPracticed: today,
  },
  {
    id: "tech-14",
    name: "Ankle Pick",
    position: "Standing",
    category: "Takedown",
    level: "Beginner",
    tags: ["grip fight", "level change"],
    notes: "Snap posture forward, step to angle, and collect ankle while driving with shoulder.",
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-15",
    name: "North-South Choke",
    position: "North-South",
    category: "Submission",
    level: "Intermediate",
    tags: ["choke", "top control"],
    notes: "Sprawl chest heavy, trap near arm, and circle head to tighten the carotid pressure.",
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-16",
    name: "Knee Slice from HQ",
    position: "Headquarters",
    category: "Pass",
    level: "Beginner",
    tags: ["passing", "pressure"],
    notes: "Win inside position from headquarters, slice knee through, and settle with crossface.",
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-17",
    name: "Technical Stand Up",
    position: "Open Guard",
    category: "Escape",
    level: "Beginner",
    tags: ["fundamental", "base"],
    notes: "Post hand and opposite foot, keep one leg as a shield, and stand while staying safe.",
    timesPracticed: 6,
    lastPracticed: today,
  },
  {
    id: "tech-18",
    name: "Tripod Sweep",
    position: "Open Guard",
    category: "Sweep",
    level: "Beginner",
    tags: ["off-balance", "fundamental"],
    notes: "Control one ankle and opposite sleeve, post your foot to their hip, and lift to topple.",
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-19",
    name: "Toreando Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Beginner",
    tags: ["mobility", "angles"],
    notes: "Redirect legs side to side with grips, then drop hips once you clear their knees.",
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-20",
    name: "Seatbelt Back Control",
    position: "Back Control",
    category: "Control",
    level: "Beginner",
    tags: ["control", "hooks"],
    notes: "Secure seatbelt first, place hooks with chest connection, and keep head tight behind theirs.",
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-21",
    name: "Lasso Guard Retention",
    position: "Lasso Guard",
    category: "Control",
    level: "Intermediate",
    tags: ["gi", "retention"],
    notes: "Thread lasso deep, angle hips out, and use sleeve tension to keep distance and recover.",
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-22",
    name: "Crab Ride Back Take",
    position: "Inversion",
    category: "Control",
    level: "Intermediate",
    tags: ["back take", "inversion"],
    notes: "Control near hip, insert crab hook, and follow hips to expose and secure the back.",
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-23",
    name: "Over Under Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Intermediate",
    tags: ["pressure", "stack"],
    notes: "Trap one leg over your shoulder, stack hips, and walk toward north-south to pass.",
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-24",
    name: "Clock Choke",
    position: "Turtle Top",
    category: "Submission",
    level: "Intermediate",
    tags: ["gi", "collar choke"],
    notes: "Deep collar feed from turtle top, step to angle, and rotate chest as you sprawl.",
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-25",
    name: "Body Triangle Finish System",
    position: "Back Control",
    category: "Control",
    level: "Advanced",
    tags: ["control", "finishing mechanics"],
    notes: "Lock body triangle on weak side, trap upper body with seatbelt, and isolate finishing arm.",
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-26",
    name: "False Reap to Heel Exposure",
    position: "Ashi Garami",
    category: "Submission",
    level: "Advanced",
    tags: ["leg locks", "entries"],
    notes: "Use false reap to expose heel line, control knee line first, then rotate for finish.",
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-27",
    name: "Armbar from Closed Guard",
    position: "Closed Guard",
    category: "Submission",
    level: "Beginner",
    tags: ["fundamental", "joint lock"],
    notes: "Break posture first and pivot before swinging the leg over.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-28",
    name: "Single Leg Takedown",
    position: "Standing",
    category: "Takedown",
    level: "Beginner",
    tags: ["wrestling", "entry"],
    notes: "Level change to penetration step, head tight to hip, then run angle to complete.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-29",
    name: "Upa Mount Escape",
    position: "Mount Bottom",
    category: "Escape",
    level: "Beginner",
    tags: ["fundamental", "bridge"],
    notes: "Trap one arm and same-side foot, bridge diagonally, and roll into top position.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-30",
    name: "Trap and Roll Side Control Escape",
    position: "Side Control Bottom",
    category: "Escape",
    level: "Beginner",
    tags: ["defense", "frames"],
    notes: "Build forearm frames, trap near arm, bridge and turn to recover guard or knees.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-31",
    name: "Pendulum Sweep",
    position: "Closed Guard",
    category: "Sweep",
    level: "Beginner",
    tags: ["off-balance", "fundamental"],
    notes: "Control posture, swing underhook leg like a pendulum, and roll them over shoulder line.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-32",
    name: "Standing Guard Break",
    position: "Closed Guard Top",
    category: "Pass",
    level: "Beginner",
    tags: ["posture", "opening guard"],
    notes: "Stand with posture, wedge knee between hips, and open guard before initiating pass.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-33",
    name: "Back Take from Seatbelt",
    position: "Turtle",
    category: "Control",
    level: "Beginner",
    tags: ["control", "hooks"],
    notes: "Secure seatbelt from turtle, insert first hook, then pull them to second hook side.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-34",
    name: "Americana from Side Control",
    position: "Side Control",
    category: "Submission",
    level: "Beginner",
    tags: ["joint lock", "top game"],
    notes: "Pin wrist, isolate elbow at 90 degrees, and rotate shoulder with controlled pressure.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-35",
    name: "Snap Down to Front Headlock",
    position: "Standing",
    category: "Takedown",
    level: "Beginner",
    tags: ["wrestling", "head control"],
    notes: "Snap their head past their base, circle to angle, and lock front headlock control.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-36",
    name: "Arm Triangle from Side Control",
    position: "Side Control",
    category: "Submission",
    level: "Intermediate",
    tags: ["choke", "pressure"],
    notes: "Thread choking arm deep, connect biceps grip, and walk body around to finish tight.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-37",
    name: "Bow and Arrow Choke",
    position: "Back Control",
    category: "Submission",
    level: "Intermediate",
    tags: ["gi", "collar choke"],
    notes: "Maintain strong collar grip, control far pant/leg, and extend hips while pulling collar.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-38",
    name: "Omoplata from Guard",
    position: "Open Guard",
    category: "Submission",
    level: "Intermediate",
    tags: ["shoulder lock", "angles"],
    notes: "Break posture, swing leg over shoulder, and sit up to control and finish the shoulder.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-39",
    name: "Kimura Trap Back Take",
    position: "Half Guard Top",
    category: "Control",
    level: "Intermediate",
    tags: ["kimura trap", "back take"],
    notes: "Trap arm with kimura grip, force turn, and follow hips to secure back control.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-40",
    name: "Sumi Gaeshi",
    position: "Standing",
    category: "Takedown",
    level: "Intermediate",
    tags: ["judo", "sacrifice throw"],
    notes: "Use belt/sleeve or overhook control, drop under center, and elevate to flip opponent.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-41",
    name: "Balloon Sweep",
    position: "Spider Guard",
    category: "Sweep",
    level: "Intermediate",
    tags: ["gi", "off-balance"],
    notes: "Load hips with spider hooks, lift as they step forward, and tip them overhead.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-42",
    name: "X-Guard Technical Stand-Up Sweep",
    position: "X-Guard",
    category: "Sweep",
    level: "Intermediate",
    tags: ["ashi", "wrestle-up"],
    notes: "Extend from X-guard to break balance, post hand, and stand up to finish sweep.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-43",
    name: "Leg Drag Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Intermediate",
    tags: ["angles", "control"],
    notes: "Staple their leg across centerline, clear knee shield, and settle chest-to-chest.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-44",
    name: "De La Riva Back Step Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Intermediate",
    tags: ["mobility", "passing"],
    notes: "Pin DLR hook, back-step hips past knee line, and flatten them before crossfacing.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-45",
    name: "Granby to Guard Recovery",
    position: "Turtle",
    category: "Escape",
    level: "Intermediate",
    tags: ["inversion", "retention"],
    notes: "Roll across shoulders with tight elbows, invert through space, and reconnect guard hooks.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-46",
    name: "Uchi Mata Entry",
    position: "Standing",
    category: "Takedown",
    level: "Advanced",
    tags: ["judo", "timing"],
    notes: "Off-balance forward, rotate hips deeply inside, and reap with lifting inner thigh.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-47",
    name: "Duck Under to Rear Body Lock",
    position: "Standing",
    category: "Takedown",
    level: "Advanced",
    tags: ["wrestling", "angles"],
    notes: "Clear tie with level change, duck under arm, and lock rear body lock to finish.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-48",
    name: "Rear Triangle from Back",
    position: "Back Control",
    category: "Submission",
    level: "Advanced",
    tags: ["triangle", "back attacks"],
    notes: "Trap one arm from back, shoot leg over shoulder line, and lock triangle behind knee.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-49",
    name: "Saddle Heel Hook Finish",
    position: "Saddle",
    category: "Submission",
    level: "Advanced",
    tags: ["leg locks", "heel hook"],
    notes: "Pin knee line in saddle, expose heel with wrist wedge, and rotate hips for finish.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-50",
    name: "Inside Sankaku Control Chain",
    position: "Inside Sankaku",
    category: "Control",
    level: "Advanced",
    tags: ["leg entanglement", "control"],
    notes: "Cross your knees tight around trapped leg, control secondary leg, and limit rotations.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-51",
    name: "Matrix Back Take from DLR",
    position: "De La Riva",
    category: "Control",
    level: "Advanced",
    tags: ["back take", "inversion"],
    notes: "Invert under far hip from DLR, connect to near hip, and climb to seatbelt.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-52",
    name: "Berimbolo to Crab Ride",
    position: "De La Riva",
    category: "Sweep",
    level: "Advanced",
    tags: ["inversion", "back take"],
    notes: "Roll under from berimbolo entry, connect crab hooks, and steer hips to back exposure.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-53",
    name: "Smash Half Guard Passing Chain",
    position: "Half Guard Top",
    category: "Pass",
    level: "Advanced",
    tags: ["pressure", "chain passing"],
    notes: "Flatten half guard with crossface/underhook and chain knee slice, back step, and smash.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-54",
    name: "Float Pass to Knee-On-Belly",
    position: "Top Passing",
    category: "Pass",
    level: "Advanced",
    tags: ["movement", "timing"],
    notes: "Float hips over frames, switch sides before re-guard, and drop to knee-on-belly.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-55",
    name: "Body Triangle Back Retention",
    position: "Back Control",
    category: "Control",
    level: "Advanced",
    tags: ["control", "retention"],
    notes: "Triangle legs on weak side, maintain chest connection, and adjust lock as they bridge.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-56",
    name: "Armbar Counter from Hitchhiker",
    position: "Armbar Defense",
    category: "Escape",
    level: "Advanced",
    tags: ["defense", "counterattack"],
    notes: "Turn thumb, hitchhiker escape to head side, then counter as opponent follows spin.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-57",
    name: "Lapel Worm Guard Sweep",
    position: "Lapel Guard",
    category: "Sweep",
    level: "Intermediate",
    tags: ["gi", "control"],
    notes: "Feed lapel around leg, anchor grips, and tilt opponent by breaking their posting base.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-58",
    name: "Anaconda Choke",
    position: "Front Headlock",
    category: "Submission",
    level: "Intermediate",
    tags: ["choke", "head and arm"],
    notes: "Thread choking arm through armpit, gable grip, and roll or sprawl to tighten choke.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-59",
    name: "D'Arce Choke",
    position: "Front Headlock",
    category: "Submission",
    level: "Intermediate",
    tags: ["choke", "no-gi"],
    notes: "Thread arm through neck/arm channel, lock biceps, and walk hips to close space.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-60",
    name: "Kouchi Gari",
    position: "Standing",
    category: "Takedown",
    level: "Beginner",
    tags: ["judo", "reap"],
    notes: "Force weight onto lead leg, reap inside ankle, and drive chest forward to finish.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-61",
    name: "Single Leg X Straight Ankle Lock",
    position: "Single Leg X",
    category: "Submission",
    level: "Intermediate",
    tags: ["leg lock", "ashi"],
    notes: "Control heel line from SLX, pinch knees, and bridge hips while keeping toes trapped.",
    timesPracticed: 0,
    lastPracticed: today,
  },
  {
    id: "tech-62",
    name: "North South Kimura",
    position: "North-South",
    category: "Submission",
    level: "Advanced",
    tags: ["kimura", "top control"],
    notes: "Isolate far arm in north-south, lock kimura grip, and rotate shoulder with chest pressure.",
    timesPracticed: 0,
    lastPracticed: today,
  },
];

export const sessionLogs: SessionLog[] = [
  {
    id: "session-1",
    date: today,
    giType: "Gi",
    sessionType: "Class",
    techniquesPracticed: ["tech-1", "tech-2", "tech-6"],
    notes: "Focused on posture breaks, passing entries, and double-leg setups.",
    rollNotes: [
      {
        partner: "Alex",
        rounds: 3,
        notes: "Got swept from DLR twice, recovered with knee cut once.",
      },
    ],
  },
  {
    id: "session-2",
    date: today,
    giType: "No-Gi",
    sessionType: "Open Mat",
    techniquesPracticed: ["tech-4", "tech-5", "tech-12"],
    notes: "Leg entanglement entries and back escape chains.",
  },
];
