import type { SessionLog, Technique } from "../types/domain";
import { localTodayIso } from "../utils/date";

const today = localTodayIso();

export const techniques: Technique[] = [
  {
    id: "tech-1",
    name: "Triangle from Guard",
    position: "Closed Guard",
    category: "Submission",
    level: "Beginner",
    tags: ["choke", "fundamental"],
    notes: "Break posture first, then angle off before locking.",
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-2",
    name: "Knee Cut Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Beginner",
    tags: ["pressure", "guard pass"],
    notes: "Control near-side underhook to avoid the back-take.",
    timesPracticed: 8,
    lastPracticed: today,
  },
  {
    id: "tech-3",
    name: "Scissor Sweep",
    position: "Guard",
    category: "Sweep",
    level: "Beginner",
    tags: ["fundamental", "off-balance"],
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-4",
    name: "Single Leg X Sweep",
    position: "Single Leg X",
    category: "Sweep",
    level: "Beginner",
    tags: ["ashi", "off-balance"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-5",
    name: "Back Escape to Half Guard",
    position: "Back Control Defense",
    category: "Escape",
    level: "Beginner",
    tags: ["defense", "survival"],
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-6",
    name: "Double Leg Takedown",
    position: "Standing",
    category: "Takedown",
    level: "Beginner",
    tags: ["wrestling", "entry"],
    notes: "Level change, head inside, run the pipe.",
    timesPracticed: 6,
    lastPracticed: today,
  },
  {
    id: "tech-7",
    name: "Arm Triangle from Mount",
    position: "Mount",
    category: "Submission",
    level: "Beginner",
    tags: ["choke", "control"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-8",
    name: "Hip Bump Sweep",
    position: "Closed Guard",
    category: "Sweep",
    level: "Beginner",
    tags: ["fundamental", "kimura threat"],
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-9",
    name: "Kimura from Side Control",
    position: "Side Control",
    category: "Submission",
    level: "Beginner",
    tags: ["shoulder lock", "top game"],
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-10",
    name: "Granby Roll",
    position: "Turtle",
    category: "Escape",
    level: "Beginner",
    tags: ["inversion", "defense"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-11",
    name: "Body Lock Pass",
    position: "Half Guard Top",
    category: "Pass",
    level: "Beginner",
    tags: ["pressure", "smash pass"],
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-12",
    name: "Berimbolo Entry",
    position: "DLR",
    category: "Sweep",
    level: "Intermediate",
    tags: ["leg entanglement", "back take"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-13",
    name: "Cross Collar Choke",
    position: "Mount",
    category: "Submission",
    level: "Beginner",
    tags: ["gi", "fundamental"],
    timesPracticed: 7,
    lastPracticed: today,
  },
  {
    id: "tech-14",
    name: "Ankle Pick",
    position: "Standing",
    category: "Takedown",
    level: "Beginner",
    tags: ["grip fight", "level change"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-15",
    name: "North-South Choke",
    position: "North-South",
    category: "Submission",
    level: "Intermediate",
    tags: ["choke", "top control"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-16",
    name: "Knee Slice from HQ",
    position: "Headquarters",
    category: "Pass",
    level: "Beginner",
    tags: ["passing", "pressure"],
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-17",
    name: "Technical Stand Up",
    position: "Open Guard",
    category: "Escape",
    level: "Beginner",
    tags: ["fundamental", "base"],
    timesPracticed: 6,
    lastPracticed: today,
  },
  {
    id: "tech-18",
    name: "Tripod Sweep",
    position: "Open Guard",
    category: "Sweep",
    level: "Beginner",
    tags: ["off-balance", "fundamental"],
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-19",
    name: "Toreando Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Beginner",
    tags: ["mobility", "angles"],
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-20",
    name: "Seatbelt Back Control",
    position: "Back Control",
    category: "Control",
    level: "Beginner",
    tags: ["control", "hooks"],
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-21",
    name: "Lasso Guard Retention",
    position: "Lasso Guard",
    category: "Control",
    level: "Intermediate",
    tags: ["gi", "retention"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-22",
    name: "Crab Ride Back Take",
    position: "Inversion",
    category: "Control",
    level: "Intermediate",
    tags: ["back take", "inversion"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-23",
    name: "Over Under Pass",
    position: "Top Passing",
    category: "Pass",
    level: "Intermediate",
    tags: ["pressure", "stack"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-24",
    name: "Clock Choke",
    position: "Turtle Top",
    category: "Submission",
    level: "Intermediate",
    tags: ["gi", "collar choke"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-25",
    name: "Body Triangle Finish System",
    position: "Back Control",
    category: "Control",
    level: "Advanced",
    tags: ["control", "finishing mechanics"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-26",
    name: "False Reap to Heel Exposure",
    position: "Ashi Garami",
    category: "Submission",
    level: "Advanced",
    tags: ["leg locks", "entries"],
    timesPracticed: 1,
    lastPracticed: today,
  },
];

export const sessionLogs: SessionLog[] = [
  {
    id: "session-1",
    date: today,
    giType: "Gi",
    sessionType: "Class",
    techniquesPracticed: ["tech-1", "tech-2", "tech-6"],
    notes: "Focused on posture breaks, passing entries, and double-leg setups.",
    rollNotes: [
      {
        partner: "Alex",
        rounds: 3,
        notes: "Got swept from DLR twice, recovered with knee cut once.",
      },
    ],
  },
  {
    id: "session-2",
    date: today,
    giType: "No-Gi",
    sessionType: "Open Mat",
    techniquesPracticed: ["tech-4", "tech-5", "tech-12"],
    notes: "Leg entanglement entries and back escape chains.",
  },
];
