import type { SessionLog, Technique } from "./types";
import { localTodayIso } from "./date";

const today = localTodayIso();

export const techniques: Technique[] = [
  {
    id: "tech-1",
    name: "Triangle from Guard",
    position: "Closed Guard",
    category: "Submission",
    beltGuideline: "White",
    tags: ["choke", "fundamental"],
    notes: "Break posture first, then angle off before locking.",
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-2",
    name: "Knee Cut Pass",
    position: "Top Passing",
    category: "Pass",
    beltGuideline: "White",
    tags: ["pressure", "guard pass"],
    notes: "Control near-side underhook to avoid the back-take.",
    timesPracticed: 8,
    lastPracticed: today,
  },
  {
    id: "tech-3",
    name: "Scissor Sweep",
    position: "Guard",
    category: "Sweep",
    beltGuideline: "White",
    tags: ["fundamental", "off-balance"],
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-4",
    name: "Single Leg X Sweep",
    position: "Single Leg X",
    category: "Sweep",
    beltGuideline: "Blue",
    tags: ["ashi", "off-balance"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-5",
    name: "Back Escape to Half Guard",
    position: "Back Control Defense",
    category: "Escape",
    beltGuideline: "Blue",
    tags: ["defense", "survival"],
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-6",
    name: "Double Leg Takedown",
    position: "Standing",
    category: "Takedown",
    beltGuideline: "White",
    tags: ["wrestling", "entry"],
    notes: "Level change, head inside, run the pipe.",
    timesPracticed: 6,
    lastPracticed: today,
  },
  {
    id: "tech-7",
    name: "Arm Triangle from Mount",
    position: "Mount",
    category: "Submission",
    beltGuideline: "Blue",
    tags: ["choke", "control"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-8",
    name: "Hip Bump Sweep",
    position: "Closed Guard",
    category: "Sweep",
    beltGuideline: "White",
    tags: ["fundamental", "kimura threat"],
    timesPracticed: 5,
    lastPracticed: today,
  },
  {
    id: "tech-9",
    name: "Kimura from Side Control",
    position: "Side Control",
    category: "Submission",
    beltGuideline: "White",
    tags: ["shoulder lock", "top game"],
    timesPracticed: 3,
    lastPracticed: today,
  },
  {
    id: "tech-10",
    name: "Granby Roll",
    position: "Turtle",
    category: "Escape",
    beltGuideline: "Blue",
    tags: ["inversion", "defense"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-11",
    name: "Body Lock Pass",
    position: "Half Guard Top",
    category: "Pass",
    beltGuideline: "Blue",
    tags: ["pressure", "smash pass"],
    timesPracticed: 4,
    lastPracticed: today,
  },
  {
    id: "tech-12",
    name: "Berimbolo Entry",
    position: "DLR",
    category: "Sweep",
    beltGuideline: "Purple",
    tags: ["leg entanglement", "back take"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-13",
    name: "Cross Collar Choke",
    position: "Mount",
    category: "Submission",
    beltGuideline: "White",
    tags: ["gi", "fundamental"],
    timesPracticed: 7,
    lastPracticed: today,
  },
  {
    id: "tech-14",
    name: "Ankle Pick",
    position: "Standing",
    category: "Takedown",
    beltGuideline: "White",
    tags: ["grip fight", "level change"],
    timesPracticed: 2,
    lastPracticed: today,
  },
  {
    id: "tech-15",
    name: "North-South Choke",
    position: "North-South",
    category: "Submission",
    beltGuideline: "Purple",
    tags: ["choke", "top control"],
    timesPracticed: 1,
    lastPracticed: today,
  },
  {
    id: "tech-16",
    name: "Knee Slice from HQ",
    position: "Headquarters",
    category: "Pass",
    beltGuideline: "Blue",
    tags: ["passing", "pressure"],
    timesPracticed: 3,
    lastPracticed: today,
  },
];

export const sessionLogs: SessionLog[] = [
  {
    id: "session-1",
    date: today,
    giType: "Gi",
    sessionType: "Class",
    techniquesPracticed: ["tech-1", "tech-2", "tech-6"],
    notes: "Focused on posture breaks, passing entries, and double-leg setups.",
    rollNotes: [
      {
        partner: "Alex",
        rounds: 3,
        notes: "Got swept from DLR twice, recovered with knee cut once.",
      },
    ],
  },
  {
    id: "session-2",
    date: today,
    giType: "No-Gi",
    sessionType: "Open Mat",
    techniquesPracticed: ["tech-4", "tech-5", "tech-12"],
    notes: "Leg entanglement entries and back escape chains.",
  },
];
